### ISSUE TITLE
Bug：The new version of the plugin will cause another plugin obsidian-shellcommands to fail

### ISSUE THREAD

**Issue by tyf2018** [nothingislost/obsidian-dynamic-highlights#25]
The new version of the plugin will cause another plugin obsidian-shellcommands to fail. The old version 0.1.2 is normal and will not conflict.

Can this compatibility issue be resolved? Thanks!

obsidian-shellcommands:  https://github.com/Taitava/obsidian-shellcommands

Best Regards.

**Comment by nothingislost** [comment]
I don't use that plugin. Can you provide some more details around how the plugin fails? If there are any errors in the dev tools console, that would be helpful.

**Comment by tyf2018** [comment]
Hi， @nothingislost 

Here is the console log.
[obsidian.md-1642819080523.log](https://github.com/nothingislost/obsidian-dynamic-highlights/files/7917490/obsidian.md-1642819080523.log)


![image](https://user-images.githubusercontent.com/56342788/150621881-a85ed5e6-730a-454c-a33a-d314a59a2350.png)

![image](https://user-images.githubusercontent.com/56342788/150621887-3b2cf157-096b-440d-8751-2e9e6cd3dc5f.png)

**Comment by Mara-Li** [comment]
Oh, so, I'm not the only one. If at last I check the issue here before I make a issue on shell commands...

So, here is the discussion in Shell commands : https://github.com/Taitava/obsidian-shellcommands/discussions/137
There is no message from Dynamic, but on Shell  : 

![image](https://user-images.githubusercontent.com/30244939/151392754-8caf798e-cbed-4423-889d-4fa3780cab2a.png)

**Comment by Taitava** [comment]
Hi, I'm the maintainer of the mentioned plugin. I'm currently in a rush and don't have time to read through this issue thoroughly. I just wanted to say that if you need any help from me inspecting this issue (or if there's anything to fix in my plugin), I'm ready to help. :slightly_smiling_face:

**Comment by Taitava** [comment]
@tyf2018 In the title you mention _The new version of the plugin will cause..._. Does _new version_ mean `0.1.3`? This can help me to look into this. If this is the case, then I can [compare the changes between `0.1.2` and `0.1.3`](https://github.com/nothingislost/obsidian-dynamic-highlights/compare/0.1.2...0.1.3).

**Comment by tyf2018** [comment]
> @tyf2018 In the title you mention _The new version of the plugin will cause..._. Does _new version_ mean `0.1.3`? 

Thanks for taking the time to fix this, the new version refers to 0.1.6.

In fact, I just also tried the 0.2.1 version of dynamic-highlights, which also caused the error.

**Comment by chrisgrieser** [comment]
I can also confirm that disabling dynamic highlights allows me to use the settings tab of Shell Commands again.

**Comment by chrisgrieser** [comment]
also, the Dynamic Highlights plugin seems to dislike shell commands so much, when I have *entered* new settings in the shell commands by disabling dynamic highlights, and then enable dynamic highlights again, it completely shuts me off from the shell commands:
<img width="1372" alt="Screenshot 2022-02-13 12 07 30" src="https://user-images.githubusercontent.com/73286100/153750397-f1a4805e-a3eb-4b1e-9eaf-8c8b8d009fb1.png">

Also, shell commands that include variables are also blocked as long as Dynamic highlights is enabled.

**Comment by nothingislost** [comment]
@Taitava this appears to be due to the fact that I'm patching RegExp Match to include capture group indices (https://github.com/tc39/proposal-regexp-match-indices) This is an additive patch and shouldn't change the default behavior of RegExp Match but it appears the fact that the match data structure now has additional fields is throwing off some of your logic: 

Without the patch 
![image](https://user-images.githubusercontent.com/89109712/153789679-cffa44de-a7d0-4dcc-95b1-5404fe33cff3.png)

With the patch
![image](https://user-images.githubusercontent.com/89109712/153789352-0cd689d8-75e1-491f-831f-d43f2fc280e5.png)

Notice the new `indices` key. That appears to be breaking your logic here: https://github.com/Taitava/obsidian-shellcommands/blob/2b05ffd955ebf57288d9cb03551267c564ff42b5/src/variables/parseShellCommandVariables.ts#L39 because it's iterating over the `indices` key and `parameter_name` is undefined 
![image](https://user-images.githubusercontent.com/89109712/153790026-4d83b899-49cd-4bfb-92c9-72d8b8617f29.png)

I'll look into what I can do to limit the scope of this patch but the ECMAScript proposal for this RegExp feature has been accepted so it would probably be good to handle it within Shell Commands if possible,

**Comment by nothingislost** [comment]
v0.2.2 of Dynamic Highlights should fix this incompatibility. The RegExp shim has been changed to not affect all instances of RegExp so it should no longer affect other plugins.

**Comment by nothingislost** [comment]
Did you restart Obsidian after upgrading Dynamic Highlights? I don't see this behavior.

**Comment by chrisgrieser** [comment]
oh right, I haven't.

After restart, everything works now. Thanks!

**Comment by Taitava** [comment]
> v0.2.2 of Dynamic Highlights should fix this incompatibility. The RegExp shim has been changed to not affect all instances of RegExp so it should no longer affect other plugins.

Thank you a lot! 😎 Nice that you found a solution! 🙂 It might have been hard for me to spot this regex issue.

> Notice the new `indices` key. That appears to be breaking your logic here: https://github.com/Taitava/obsidian-shellcommands/blob/2b05ffd955ebf57288d9cb03551267c564ff42b5/src/variables/parseShellCommandVariables.ts#L39 because it's iterating over the `indices` key and `parameter_name` is undefined ![image](https://user-images.githubusercontent.com/89109712/153790026-4d83b899-49cd-4bfb-92c9-72d8b8617f29.png)
> 
> I'll look into what I can do to limit the scope of this patch but **the ECMAScript proposal for this RegExp feature has been accepted so it would probably be good to handle it within Shell Commands** if possible,

I'll definitely need to change that part of the code. I created a new issue for SC for fixing it: https://github.com/Taitava/obsidian-shellcommands/issues/152

**Comment by Taitava** [comment]
Just for the record, [I've fixed the bad logic in my plugin now](https://github.com/Taitava/obsidian-shellcommands/issues/152). The fix is just not released yet, but will be in SC `0.11.0`. Thank you to everybody for the co-operation! 😎
